-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-10-05T07:48:10.597Z

CREATE TYPE "academic_rank" AS ENUM (
  'lecturer',
  'asst_prof',
  'assoc_prof',
  'prof'
);

CREATE TYPE "position_code" AS ENUM (
  'dean',
  'vice_dean',
  'asst_dean',
  'exec_committee',
  'dept_chair',
  'dept_deputy',
  'dept_secretary',
  'dept_committee'
);

CREATE TYPE "submission_status" AS ENUM (
  'draft',
  'submitted',
  'assessing',
  'dept_review',
  'returned',
  'dept_approved',
  'sent_to_faculty'
);

CREATE TYPE "signer_role" AS ENUM (
  'performer',
  'receiver',
  'dept_chair',
  'dept_committee'
);

CREATE TYPE "approval_decision" AS ENUM (
  'approved',
  'returned'
);

CREATE TYPE "weight_mode" AS ENUM (
  'fixed',
  'ranged'
);

CREATE TYPE "range_basis" AS ENUM (
  'weight',
  'points'
);

CREATE TYPE "assessment_agg" AS ENUM (
  'none',
  'single',
  'average'
);

CREATE TYPE "quantity_unit" AS ENUM (
  'credit',
  'topic',
  'course',
  'hour',
  'person',
  'term'
);

CREATE TYPE "data_source" AS ENUM (
  'manual',
  'registrar',
  'registrar_edited'
);

CREATE TYPE "evidence_status" AS ENUM (
  'pending',
  'uploaded'
);

CREATE TABLE "department" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(10) UNIQUE NOT NULL,
  "name_th" varchar(150) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "lecturer" (
  "lecturer_id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "cognito_sub" varchar(64) UNIQUE,
  "department_id" smallint,
  "name_th" varchar(255) NOT NULL,
  "name_en" varchar(255),
  "rank" varchar(100),
  "profile_image_url" text,
  "office" varchar(255),
  "phone" varchar(50),
  "phone_extension" varchar(50),
  "email" varchar(255) UNIQUE NOT NULL,
  "cv_url" text,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now()),
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "education" (
  "education_id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lecturer_id" uuid NOT NULL,
  "degree" varchar(100),
  "field" varchar(255),
  "institution" varchar(500),
  "country" varchar(100),
  "graduation_year" varchar(10)
);

CREATE TABLE "research_interest" (
  "research_interest_id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "faculty_research_interest" (
  "lecturer_id" uuid NOT NULL,
  "research_interest_id" smallint NOT NULL,
  PRIMARY KEY ("lecturer_id", "research_interest_id")
);

CREATE TABLE "expertise" (
  "expertise_id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" text NOT NULL
);

CREATE TABLE "faculty_expertise" (
  "lecturer_id" uuid NOT NULL,
  "expertise_id" smallint NOT NULL,
  PRIMARY KEY ("lecturer_id", "expertise_id")
);

CREATE TABLE "publication" (
  "publication_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "publication_year" smallint,
  "venue" text,
  "volume" varchar(50),
  "pages" varchar(50),
  "doi" varchar(255) UNIQUE,
  "citation_text" text,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "faculty_publication" (
  "lecturer_id" uuid NOT NULL,
  "publication_id" int NOT NULL,
  "author_order" smallint,
  PRIMARY KEY ("lecturer_id", "publication_id")
);

CREATE TABLE "publication_profile" (
  "publication_profile_id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lecturer_id" uuid NOT NULL,
  "provider" varchar(100) NOT NULL,
  "url" text NOT NULL
);

CREATE TABLE "member_position" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "lecturer_id" uuid NOT NULL,
  "position" position_code NOT NULL,
  "department_id" smallint,
  "start_date" date NOT NULL,
  "end_date" date
);

CREATE TABLE "rubric_version" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(30) UNIQUE NOT NULL,
  "approved_meeting" varchar(50),
  "approved_on" date,
  "base_points" numeric(6,2) NOT NULL DEFAULT 200,
  "overall_cap" numeric(8,2) NOT NULL DEFAULT 2000,
  "min_required" numeric(8,2) NOT NULL DEFAULT 650,
  "min_teaching_credits" numeric(5,2) NOT NULL DEFAULT 6,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rubric_category" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "version_id" smallint NOT NULL,
  "code" varchar(5) NOT NULL,
  "name_th" varchar(100) NOT NULL,
  "cap" numeric(8,2) NOT NULL,
  "sort_order" smallint NOT NULL
);

CREATE TABLE "rubric_section" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" smallint NOT NULL,
  "parent_id" smallint,
  "code" varchar(10) NOT NULL,
  "name_th" varchar(255) NOT NULL,
  "cap" numeric(8,2),
  "max_entries" smallint,
  "sort_order" smallint NOT NULL
);

CREATE TABLE "rubric_item" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "section_id" smallint NOT NULL,
  "label_th" varchar(255) NOT NULL,
  "weight_mode" weight_mode NOT NULL DEFAULT 'fixed',
  "weight" numeric(6,4),
  "weight_min" numeric(8,4),
  "weight_max" numeric(8,4),
  "range_basis" range_basis,
  "assessor_position" position_code,
  "assessment_agg" assessment_agg NOT NULL DEFAULT 'none',
  "unit" quantity_unit NOT NULL,
  "unit_divisor" numeric(6,2) NOT NULL DEFAULT 1,
  "uses_participation" boolean NOT NULL DEFAULT false,
  "counts_teaching_credit" boolean NOT NULL DEFAULT false,
  "once_per_round" boolean NOT NULL DEFAULT false,
  "tier_min" integer,
  "tier_max" integer,
  "field_schema" jsonb,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "evaluation_round" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rubric_version_id" smallint NOT NULL,
  "name_th" varchar(100) NOT NULL,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  "salary_effective_on" date NOT NULL,
  "academic_year" smallint NOT NULL,
  "semester" smallint,
  "submit_due_at" timestamptz,
  "is_open" boolean NOT NULL DEFAULT false
);

CREATE TABLE "submission" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "round_id" smallint NOT NULL,
  "lecturer_id" uuid NOT NULL,
  "status" submission_status NOT NULL DEFAULT 'draft',
  "rank_snapshot" academic_rank NOT NULL,
  "department_snapshot" smallint NOT NULL,
  "teaching_credits" numeric(6,2) NOT NULL DEFAULT 0,
  "raw_total" numeric(8,2) NOT NULL DEFAULT 0,
  "capped_total" numeric(8,2) NOT NULL DEFAULT 0,
  "submitted_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "submission_entry" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "submission_id" uuid NOT NULL,
  "item_id" smallint NOT NULL,
  "title" varchar(500),
  "course_code" varchar(15),
  "section_no" varchar(10),
  "student_count" integer,
  "data_source" data_source NOT NULL DEFAULT 'manual',
  "synced_at" timestamptz,
  "quantity" numeric(8,2) NOT NULL DEFAULT 1,
  "participation_pct" numeric(5,2) NOT NULL DEFAULT 100,
  "weight_applied" numeric(8,4),
  "credits" numeric(5,2),
  "score" numeric(8,2) NOT NULL DEFAULT 0,
  "details" jsonb,
  "note" text,
  "sort_order" smallint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "entry_assessment" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "entry_id" uuid NOT NULL,
  "assessor_id" uuid NOT NULL,
  "position_used" position_code NOT NULL,
  "value_given" numeric(8,4) NOT NULL,
  "comment" text,
  "assessed_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "entry_evidence" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "entry_id" uuid NOT NULL,
  "ref_code" varchar(50),
  "label" varchar(255),
  "s3_key" varchar(512) UNIQUE NOT NULL,
  "file_name" varchar(255) NOT NULL,
  "mime_type" varchar(100) NOT NULL,
  "size_bytes" bigint NOT NULL,
  "checksum" char(64),
  "status" evidence_status NOT NULL DEFAULT 'pending',
  "uploaded_by" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "submission_category_total" (
  "submission_id" uuid,
  "category_id" smallint,
  "raw_score" numeric(8,2) NOT NULL,
  "capped_score" numeric(8,2) NOT NULL,
  PRIMARY KEY ("submission_id", "category_id")
);

CREATE TABLE "submission_approval" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "submission_id" uuid NOT NULL,
  "signer_id" uuid NOT NULL,
  "role" signer_role NOT NULL,
  "decision" approval_decision NOT NULL,
  "comment" text,
  "signed_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE UNIQUE INDEX ON "publication_profile" ("lecturer_id", "provider", "url");

CREATE INDEX ON "member_position" ("lecturer_id", "start_date");

CREATE INDEX ON "member_position" ("position", "department_id");

CREATE UNIQUE INDEX ON "rubric_category" ("version_id", "code");

CREATE UNIQUE INDEX ON "rubric_section" ("category_id", "code");

CREATE UNIQUE INDEX ON "submission" ("round_id", "lecturer_id");

CREATE INDEX ON "submission" ("round_id", "status");

CREATE INDEX ON "submission_entry" ("submission_id", "item_id");

CREATE INDEX ON "submission_entry" ("course_code", "section_no");

CREATE UNIQUE INDEX ON "entry_assessment" ("entry_id", "assessor_id");

CREATE INDEX ON "entry_evidence" ("entry_id");

CREATE INDEX ON "entry_evidence" ("status");

CREATE INDEX ON "submission_approval" ("submission_id", "signed_at");

COMMENT ON TABLE "department" IS 'สาขาวิชา - ยกมาจาก SemesterReport ให้เป็น master กลาง (lecturer ก็ผูกกับตัวนี้)';

COMMENT ON TABLE "lecturer" IS 'ตารางเดียวที่เชื่อม Academic_Portfolio กับ SemesterReport
PK ชื่อ lecturer_id (ตามของเดิมที่ backend ใช้อยู่แล้ว ไม่ใช่ id แบบที่ SemesterReport ออกแบบไว้ตอนแรก)
';

COMMENT ON COLUMN "lecturer"."cognito_sub" IS 'sub จาก Cognito — NULL ได้ชั่วคราวสำหรับอาจารย์ที่ยังไม่ผูก auth (ของเดิมไม่มีคอลัมน์นี้)';

COMMENT ON COLUMN "lecturer"."department_id" IS 'NULL ได้ชั่วคราวจนข้อมูลสาขาของอาจารย์เดิมพร้อม ค่อยบังคับ NOT NULL';

COMMENT ON COLUMN "lecturer"."rank" IS 'ข้อความอิสระเหมือนเดิม — ไม่แปลงเป็น academic_rank enum เพื่อไม่กระทบ model/DTO เดิม';

COMMENT ON TABLE "member_position" IS 'เป็นทั้ง role ผู้ประเมิน และข้อมูลคะแนนข้อ 3.1/3.2 ของฟอร์มภาระงาน';

COMMENT ON COLUMN "member_position"."department_id" IS 'NULL = ตำแหน่งระดับคณะ (คณบดี/กรรมการบริหาร)';

COMMENT ON COLUMN "member_position"."end_date" IS 'NULL = ยังดำรงตำแหน่งอยู่';

COMMENT ON COLUMN "submission"."rank_snapshot" IS 'map จาก lecturer.rank (varchar) เป็น enum ตอน submit';

COMMENT ON COLUMN "submission_entry"."submission_id" IS 'ON DELETE CASCADE';

COMMENT ON COLUMN "entry_assessment"."entry_id" IS 'ON DELETE CASCADE';

COMMENT ON COLUMN "entry_evidence"."entry_id" IS 'ON DELETE CASCADE';

ALTER TABLE "lecturer" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "member_position" ADD FOREIGN KEY ("lecturer_id") REFERENCES "lecturer" ("lecturer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "member_position" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_category" ADD FOREIGN KEY ("version_id") REFERENCES "rubric_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_section" ADD FOREIGN KEY ("category_id") REFERENCES "rubric_category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_section" ADD FOREIGN KEY ("parent_id") REFERENCES "rubric_section" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_item" ADD FOREIGN KEY ("section_id") REFERENCES "rubric_section" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evaluation_round" ADD FOREIGN KEY ("rubric_version_id") REFERENCES "rubric_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission" ADD FOREIGN KEY ("round_id") REFERENCES "evaluation_round" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission" ADD FOREIGN KEY ("lecturer_id") REFERENCES "lecturer" ("lecturer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission" ADD FOREIGN KEY ("department_snapshot") REFERENCES "department" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_entry" ADD FOREIGN KEY ("submission_id") REFERENCES "submission" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_entry" ADD FOREIGN KEY ("item_id") REFERENCES "rubric_item" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_assessment" ADD FOREIGN KEY ("entry_id") REFERENCES "submission_entry" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_assessment" ADD FOREIGN KEY ("assessor_id") REFERENCES "lecturer" ("lecturer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_evidence" ADD FOREIGN KEY ("entry_id") REFERENCES "submission_entry" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_evidence" ADD FOREIGN KEY ("uploaded_by") REFERENCES "lecturer" ("lecturer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_category_total" ADD FOREIGN KEY ("submission_id") REFERENCES "submission" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_category_total" ADD FOREIGN KEY ("category_id") REFERENCES "rubric_category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_approval" ADD FOREIGN KEY ("submission_id") REFERENCES "submission" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_approval" ADD FOREIGN KEY ("signer_id") REFERENCES "lecturer" ("lecturer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "education" ADD FOREIGN KEY ("lecturer_id") REFERENCES "lecturer" ("lecturer_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "faculty_research_interest" ADD FOREIGN KEY ("lecturer_id") REFERENCES "lecturer" ("lecturer_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "faculty_research_interest" ADD FOREIGN KEY ("research_interest_id") REFERENCES "research_interest" ("research_interest_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "faculty_expertise" ADD FOREIGN KEY ("lecturer_id") REFERENCES "lecturer" ("lecturer_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "faculty_expertise" ADD FOREIGN KEY ("expertise_id") REFERENCES "expertise" ("expertise_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "faculty_publication" ADD FOREIGN KEY ("lecturer_id") REFERENCES "lecturer" ("lecturer_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "faculty_publication" ADD FOREIGN KEY ("publication_id") REFERENCES "publication" ("publication_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "publication_profile" ADD FOREIGN KEY ("lecturer_id") REFERENCES "lecturer" ("lecturer_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
