CREATE TYPE "academic_rank" AS ENUM (
  'lecturer',
  'asst_prof',
  'assoc_prof',
  'prof'
);

CREATE TYPE "position_code" AS ENUM (
  'dean',
  'vice_dean',
  'asst_dean',
  'exec_committee',
  'dept_chair',
  'dept_deputy',
  'dept_secretary',
  'dept_committee'
);

CREATE TYPE "submission_status" AS ENUM (
  'draft',
  'submitted',
  'assessing',
  'dept_review',
  'returned',
  'dept_approved',
  'sent_to_faculty'
);

CREATE TYPE "signer_role" AS ENUM (
  'performer',
  'receiver',
  'dept_chair',
  'dept_committee'
);

CREATE TYPE "approval_decision" AS ENUM (
  'approved',
  'returned'
);

CREATE TYPE "weight_mode" AS ENUM (
  'fixed',
  'ranged'
);

CREATE TYPE "range_basis" AS ENUM (
  'weight',
  'points'
);

CREATE TYPE "assessment_agg" AS ENUM (
  'none',
  'single',
  'average'
);

CREATE TYPE "quantity_unit" AS ENUM (
  'credit',
  'topic',
  'course',
  'hour',
  'person',
  'term'
);

CREATE TYPE "data_source" AS ENUM (
  'manual',
  'registrar',
  'registrar_edited'
);

CREATE TYPE "evidence_status" AS ENUM (
  'pending',
  'uploaded'
);

CREATE TABLE "department" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(10) UNIQUE NOT NULL,
  "name_th" varchar(150) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "lecturer" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "cognito_sub" varchar(64) UNIQUE NOT NULL,
  "name_th" varchar(255) NOT NULL,
  "name_en" varchar(255),
  "email" varchar(255) UNIQUE NOT NULL,
  "department_id" smallint NOT NULL,
  "rank" academic_rank NOT NULL,
  "profile_image_url" text,
  "office" varchar(255),
  "phone" varchar(50),
  "phone_extension" varchar(50),
  "cv_url" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "member_position" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "lecturer_id" uuid NOT NULL,
  "position" position_code NOT NULL,
  "department_id" smallint,
  "start_date" date NOT NULL,
  "end_date" date
);

CREATE TABLE "rubric_version" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(30) UNIQUE NOT NULL,
  "approved_meeting" varchar(50),
  "approved_on" date,
  "base_points" numeric(6,2) NOT NULL DEFAULT 200,
  "overall_cap" numeric(8,2) NOT NULL DEFAULT 2000,
  "min_required" numeric(8,2) NOT NULL DEFAULT 650,
  "min_teaching_credits" numeric(5,2) NOT NULL DEFAULT 6,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rubric_category" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "version_id" smallint NOT NULL,
  "code" varchar(5) NOT NULL,
  "name_th" varchar(100) NOT NULL,
  "cap" numeric(8,2) NOT NULL,
  "sort_order" smallint NOT NULL
);

CREATE TABLE "rubric_section" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" smallint NOT NULL,
  "parent_id" smallint,
  "code" varchar(10) NOT NULL,
  "name_th" varchar(255) NOT NULL,
  "cap" numeric(8,2),
  "max_entries" smallint,
  "sort_order" smallint NOT NULL
);

CREATE TABLE "rubric_item" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "section_id" smallint NOT NULL,
  "label_th" varchar(255) NOT NULL,
  "weight_mode" weight_mode NOT NULL DEFAULT 'fixed',
  "weight" numeric(6,4),
  "weight_min" numeric(8,4),
  "weight_max" numeric(8,4),
  "range_basis" range_basis,
  "assessor_position" position_code,
  "assessment_agg" assessment_agg NOT NULL DEFAULT 'none',
  "unit" quantity_unit NOT NULL,
  "unit_divisor" numeric(6,2) NOT NULL DEFAULT 1,
  "uses_participation" boolean NOT NULL DEFAULT false,
  "counts_teaching_credit" boolean NOT NULL DEFAULT false,
  "once_per_round" boolean NOT NULL DEFAULT false,
  "tier_min" integer,
  "tier_max" integer,
  "field_schema" jsonb,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "evaluation_round" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rubric_version_id" smallint NOT NULL,
  "name_th" varchar(100) NOT NULL,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  "salary_effective_on" date NOT NULL,
  "academic_year" smallint NOT NULL,
  "semester" smallint,
  "submit_due_at" timestamptz,
  "is_open" boolean NOT NULL DEFAULT false
);

CREATE TABLE "submission" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "round_id" smallint NOT NULL,
  "lecturer_id" uuid NOT NULL,
  "status" submission_status NOT NULL DEFAULT 'draft',
  "rank_snapshot" academic_rank NOT NULL,
  "department_snapshot" smallint NOT NULL,
  "teaching_credits" numeric(6,2) NOT NULL DEFAULT 0,
  "raw_total" numeric(8,2) NOT NULL DEFAULT 0,
  "capped_total" numeric(8,2) NOT NULL DEFAULT 0,
  "submitted_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "submission_entry" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "submission_id" uuid NOT NULL,
  "item_id" smallint NOT NULL,
  "title" varchar(500),
  "course_code" varchar(15),
  "section_no" varchar(10),
  "student_count" integer,
  "data_source" data_source NOT NULL DEFAULT 'manual',
  "synced_at" timestamptz,
  "quantity" numeric(8,2) NOT NULL DEFAULT 1,
  "participation_pct" numeric(5,2) NOT NULL DEFAULT 100,
  "weight_applied" numeric(8,4),
  "credits" numeric(5,2),
  "score" numeric(8,2) NOT NULL DEFAULT 0,
  "details" jsonb,
  "note" text,
  "sort_order" smallint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "entry_assessment" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "entry_id" uuid NOT NULL,
  "assessor_id" uuid NOT NULL,
  "position_used" position_code NOT NULL,
  "value_given" numeric(8,4) NOT NULL,
  "comment" text,
  "assessed_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "entry_evidence" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "entry_id" uuid NOT NULL,
  "ref_code" varchar(50),
  "label" varchar(255),
  "s3_key" varchar(512) UNIQUE NOT NULL,
  "file_name" varchar(255) NOT NULL,
  "mime_type" varchar(100) NOT NULL,
  "size_bytes" bigint NOT NULL,
  "checksum" char(64),
  "status" evidence_status NOT NULL DEFAULT 'pending',
  "uploaded_by" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "submission_category_total" (
  "submission_id" uuid,
  "category_id" smallint,
  "raw_score" numeric(8,2) NOT NULL,
  "capped_score" numeric(8,2) NOT NULL,
  PRIMARY KEY ("submission_id", "category_id")
);

CREATE TABLE "submission_approval" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "submission_id" uuid NOT NULL,
  "signer_id" uuid NOT NULL,
  "role" signer_role NOT NULL,
  "decision" approval_decision NOT NULL,
  "comment" text,
  "signed_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX ON "member_position" ("lecturer_id", "start_date");

CREATE INDEX ON "member_position" ("position", "department_id");

CREATE UNIQUE INDEX ON "rubric_category" ("version_id", "code");

CREATE UNIQUE INDEX ON "rubric_section" ("category_id", "code");

CREATE UNIQUE INDEX ON "submission" ("round_id", "lecturer_id");

CREATE INDEX ON "submission" ("round_id", "status");

CREATE INDEX ON "submission_entry" ("submission_id", "item_id");

CREATE INDEX ON "submission_entry" ("course_code", "section_no");

CREATE UNIQUE INDEX ON "entry_assessment" ("entry_id", "assessor_id");

CREATE INDEX ON "entry_evidence" ("entry_id");

CREATE INDEX ON "entry_evidence" ("status");

CREATE INDEX ON "submission_approval" ("submission_id", "signed_at");

COMMENT ON TABLE "department" IS 'สาขาวิชา - สิทธิ์ผู้ประเมินและรายงานสรุปผูกกับสาขา';

COMMENT ON TABLE "lecturer" IS 'เงาของ Cognito - ไม่เก็บ password/MFA
Cognito group คุม role กว้าง ๆ (faculty / staff / student)
ส่วนใครมีสิทธิ์ประเมินใคร อยู่ที่ member_position เพราะผูกกับสาขาและช่วงเวลา
';

COMMENT ON COLUMN "lecturer"."cognito_sub" IS 'sub จาก Cognito = จุดเชื่อมกับ auth';

COMMENT ON TABLE "member_position" IS 'ตารางนี้ทำงาน 2 อย่างพร้อมกัน จึงคุ้มที่จะมี:
1. เป็น role ผู้ประเมิน - ระบบรู้ว่าใครประเมินหมวด 3 ของใครได้ในรอบนั้น
   (Cognito group ทำแทนไม่ได้ เพราะสิทธิ์ขึ้นกับสาขา + ช่วงวันที่ + เปลี่ยนทุกวาระ)
2. เป็นข้อมูลคะแนนข้อ 3.1/3.2 เอง - ฟอร์มต้องการวันที่ดำรงตำแหน่งเพื่อคิดตามสัดส่วน
';

COMMENT ON COLUMN "member_position"."department_id" IS 'NULL = ตำแหน่งระดับคณะ (คณบดี/กรรมการบริหาร)';

COMMENT ON COLUMN "member_position"."start_date" IS 'ช่องวันที่ดำรงตำแหน่ง ในฟอร์มข้อ 3.1/3.2';

COMMENT ON COLUMN "member_position"."end_date" IS 'NULL = ยังดำรงตำแหน่งอยู่';

COMMENT ON TABLE "rubric_version" IS 'เกณฑ์ผ่านมติประชุมและแก้ทุกปี - ถ้าแก้ทับของเดิม คะแนนที่เซ็นอนุมัติไปแล้วจะคำนวณใหม่ไม่ตรง';

COMMENT ON COLUMN "rubric_version"."code" IS 'เช่น 2567-r1';

COMMENT ON COLUMN "rubric_version"."approved_meeting" IS 'เช่น 6/2567';

COMMENT ON COLUMN "rubric_category"."code" IS '1-5';

COMMENT ON COLUMN "rubric_category"."cap" IS '900/900/400/300/100';

COMMENT ON COLUMN "rubric_section"."parent_id" IS 'self-FK รองรับ 2.3 -> 2.3.1..2.3.5';

COMMENT ON COLUMN "rubric_section"."cap" IS '1.3=120, 1.4=200, 3.3=75, 4.4=100';

COMMENT ON COLUMN "rubric_section"."max_entries" IS '4.1.1 ไม่เกิน 20 คำสั่ง, 4.2.1 ไม่เกิน 10';

COMMENT ON TABLE "rubric_item" IS 'หนึ่งแถว = หนึ่งตัวเลือกในช่องชนิดงาน/หน้าที่ ของฟอร์ม';

COMMENT ON COLUMN "rubric_item"."weight" IS 'ใช้เมื่อ fixed';

COMMENT ON COLUMN "rubric_item"."weight_min" IS 'ใช้เมื่อ ranged';

COMMENT ON COLUMN "rubric_item"."range_basis" IS 'ค่าที่ผู้ประเมินให้ เป็นน้ำหนักหรือคะแนนตรง ๆ';

COMMENT ON COLUMN "rubric_item"."assessor_position" IS 'ใครมีสิทธิ์ประเมินข้อนี้ - join กับ member_position';

COMMENT ON COLUMN "rubric_item"."unit_divisor" IS 'บรรยาย ป.ตรี = 3';

COMMENT ON COLUMN "rubric_item"."once_per_round" IS '2.9 เลือกได้ 1 ข้อ';

COMMENT ON COLUMN "rubric_item"."tier_min" IS 'ช่วงจำนวน นศ. ที่ใช้ item นี้ เช่น <100 = 1.0';

COMMENT ON COLUMN "rubric_item"."tier_max" IS 'พอ API ทะเบียนมา ระบบเลือก item ให้อัตโนมัติจากจำนวน นศ.';

COMMENT ON COLUMN "rubric_item"."field_schema" IS 'ฟิลด์เสริมของข้อนั้น เช่น quartile, budget';

COMMENT ON COLUMN "evaluation_round"."salary_effective_on" IS 'วันเลื่อนเงินเดือน';

COMMENT ON COLUMN "submission"."teaching_credits" IS 'ต้องไม่ต่ำกว่า 6';

COMMENT ON TABLE "submission_entry" IS 'ตารางเดียวแทนข้อย่อย 1.1-4.6 ทั้งหมด - ลบได้เฉพาะตอน draft จึงไม่ต้อง soft delete';

COMMENT ON COLUMN "submission_entry"."submission_id" IS 'ON DELETE CASCADE';

COMMENT ON COLUMN "submission_entry"."title" IS 'ชื่อเรื่อง/โครงการ/ผลงาน/ชื่อนักศึกษา';

COMMENT ON COLUMN "submission_entry"."course_code" IS 'text เฉย ๆ - ระบบนี้ไม่ใช่เจ้าของข้อมูลรายวิชา';

COMMENT ON COLUMN "submission_entry"."section_no" IS 'sec - ใช้ตอน sync กับทะเบียน';

COMMENT ON COLUMN "submission_entry"."student_count" IS 'ยกเป็นคอลัมน์เพราะเป็นตัวกำหนดน้ำหนัก 1.0-1.3 ต้อง query/ตรวจได้';

COMMENT ON COLUMN "submission_entry"."data_source" IS 'บอกว่าตัวเลขมาจากมือหรือ API';

COMMENT ON COLUMN "submission_entry"."synced_at" IS 'ครั้งล่าสุดที่ดึงจากทะเบียน';

COMMENT ON COLUMN "submission_entry"."weight_applied" IS 'snapshot น้ำหนักที่ใช้จริง - NULL ระหว่างรอผู้ประเมินให้ค่า';

COMMENT ON COLUMN "submission_entry"."details" IS 'ฟิลด์ที่ใช้ไม่กี่ข้อ เช่น hours, quartile, budget';

COMMENT ON TABLE "entry_assessment" IS 'แยกจาก submission_entry เพราะ:
1. ข้อ 3.1 ประเมินโดยกรรมการบริหารหลายคน ต้องเก็บรายคนแล้วค่อยเฉลี่ย
2. อาจารย์เจ้าของฟอร์มต้องแก้ค่านี้ไม่ได้ - แยกตารางแล้วตัดสิทธิ์ที่ระดับ API ได้ตรง ๆ
3. เก็บได้ว่าใครให้เท่าไรเมื่อไร ใช้ตอนมีข้อโต้แย้ง
';

COMMENT ON COLUMN "entry_assessment"."entry_id" IS 'ON DELETE CASCADE';

COMMENT ON COLUMN "entry_assessment"."position_used" IS 'snapshot ตำแหน่งที่ใช้สิทธิ์ประเมิน - วาระหมดแล้วยังตรวจย้อนหลังได้';

COMMENT ON COLUMN "entry_assessment"."value_given" IS 'ต้องอยู่ในช่วง weight_min..weight_max ของ item';

COMMENT ON TABLE "entry_evidence" IS 'ไม่เก็บ bucket/region ในตาราง - เป็น config ของ deployment ไม่ใช่ข้อมูล
status=pending จำเป็นเพราะ flow presigned URL ต้องสร้างแถวก่อนไฟล์ขึ้นจริง
';

COMMENT ON COLUMN "entry_evidence"."entry_id" IS 'ON DELETE CASCADE';

COMMENT ON COLUMN "entry_evidence"."ref_code" IS 'เช่น RG301-2025-000076 (wolf) หรือเลขคำสั่ง';

COMMENT ON COLUMN "entry_evidence"."label" IS 'เช่น คำสั่งแต่งตั้ง / ใบรับรองสัดส่วน / Quartile Scimago';

COMMENT ON COLUMN "entry_evidence"."file_name" IS 'ชื่อไฟล์เดิมของผู้ใช้ ใช้ตอนให้ดาวน์โหลด';

COMMENT ON COLUMN "entry_evidence"."checksum" IS 'SHA-256 - กันไฟล์ซ้ำและยืนยันว่าไฟล์ไม่ถูกเปลี่ยนหลังอนุมัติ';

COMMENT ON TABLE "submission_category_total" IS 'ตารางสรุปรวมคะแนน 5 หมวดหน้าแรก - freeze ตอนส่ง ไม่ให้ผลที่เซ็นแล้วเปลี่ยนตาม rubric';

COMMENT ON TABLE "submission_approval" IS 'แทนช่องลงนามท้ายฟอร์ม (ผู้ปฏิบัติงาน/ผู้รับฟอร์ม/ประธาน+กรรมการสาขา)';

ALTER TABLE "lecturer" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "member_position" ADD FOREIGN KEY ("lecturer_id") REFERENCES "lecturer" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "member_position" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_category" ADD FOREIGN KEY ("version_id") REFERENCES "rubric_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_section" ADD FOREIGN KEY ("category_id") REFERENCES "rubric_category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_section" ADD FOREIGN KEY ("parent_id") REFERENCES "rubric_section" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_item" ADD FOREIGN KEY ("section_id") REFERENCES "rubric_section" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evaluation_round" ADD FOREIGN KEY ("rubric_version_id") REFERENCES "rubric_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission" ADD FOREIGN KEY ("round_id") REFERENCES "evaluation_round" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission" ADD FOREIGN KEY ("lecturer_id") REFERENCES "lecturer" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission" ADD FOREIGN KEY ("department_snapshot") REFERENCES "department" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_entry" ADD FOREIGN KEY ("submission_id") REFERENCES "submission" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_entry" ADD FOREIGN KEY ("item_id") REFERENCES "rubric_item" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_assessment" ADD FOREIGN KEY ("entry_id") REFERENCES "submission_entry" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_assessment" ADD FOREIGN KEY ("assessor_id") REFERENCES "lecturer" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_evidence" ADD FOREIGN KEY ("entry_id") REFERENCES "submission_entry" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_evidence" ADD FOREIGN KEY ("uploaded_by") REFERENCES "lecturer" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_category_total" ADD FOREIGN KEY ("submission_id") REFERENCES "submission" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_category_total" ADD FOREIGN KEY ("category_id") REFERENCES "rubric_category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_approval" ADD FOREIGN KEY ("submission_id") REFERENCES "submission" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_approval" ADD FOREIGN KEY ("signer_id") REFERENCES "lecturer" ("id") DEFERRABLE INITIALLY IMMEDIATE;
