-- Faculty workload (SemesterReport) schema, on top of 002_lecturer_profile.sql
-- Target: Aurora PostgreSQL compatible SQL (PostgreSQL 15+)
--
-- Brings a 002 database up to the merged design in
-- database/data_schema/FacultyPortfolioWorkload/FacultyPortfolioWorkload.dbml (.sql is its export):
--   * new master table `department`, and `lecturer` gets `cognito_sub` + `department_id`
--   * the workload tables (member_position, rubric_*, evaluation_round, submission*, entry_*)
-- The Academic Portfolio tables of 002 are unchanged.
--
-- Differences from the dbdiagram export (it cannot draw these, see the end of the .dbml):
--   * submission_entry.submission_id, entry_assessment.entry_id and entry_evidence.entry_id
--     are ON DELETE CASCADE (the design marks them only in a note)
--   * CHECK constraints, partial/GIN indexes, the draft-only trigger and v_section_total
--   * indexes are created without CONCURRENTLY, because that cannot run inside a transaction
--
-- 002 + this file are the source of truth; backend/app/v2/models mirrors them.

BEGIN;

CREATE TYPE "academic_rank" AS ENUM ('lecturer', 'asst_prof', 'assoc_prof', 'prof');

CREATE TYPE "position_code" AS ENUM (
  'dean',
  'vice_dean',
  'asst_dean',
  'exec_committee',
  'dept_chair',
  'dept_deputy',
  'dept_secretary',
  'dept_committee'
);

CREATE TYPE "submission_status" AS ENUM (
  'draft',
  'submitted',
  'assessing',
  'dept_review',
  'returned',
  'dept_approved',
  'sent_to_faculty'
);

CREATE TYPE "signer_role" AS ENUM ('performer', 'receiver', 'dept_chair', 'dept_committee');

CREATE TYPE "approval_decision" AS ENUM ('approved', 'returned');

CREATE TYPE "weight_mode" AS ENUM ('fixed', 'ranged');

CREATE TYPE "range_basis" AS ENUM ('weight', 'points');

CREATE TYPE "assessment_agg" AS ENUM ('none', 'single', 'average');

CREATE TYPE "quantity_unit" AS ENUM ('credit', 'topic', 'course', 'hour', 'person', 'term');

CREATE TYPE "data_source" AS ENUM ('manual', 'registrar', 'registrar_edited');

CREATE TYPE "evidence_status" AS ENUM ('pending', 'uploaded');

-- ---------------------------------------------------------------------
-- Shared master + lecturer
-- ---------------------------------------------------------------------

CREATE TABLE "department" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(10) UNIQUE NOT NULL,
  "name_th" varchar(150) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true
);

-- Both columns are nullable for now: existing lecturers have no Cognito account or department yet.
ALTER TABLE "lecturer" ADD COLUMN "cognito_sub" varchar(64) UNIQUE;
ALTER TABLE "lecturer" ADD COLUMN "department_id" smallint;

-- ---------------------------------------------------------------------
-- Administrative positions
-- ---------------------------------------------------------------------

CREATE TABLE "member_position" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "lecturer_id" uuid NOT NULL,
  "position" position_code NOT NULL,
  "department_id" smallint,
  "start_date" date NOT NULL,
  "end_date" date,
  CONSTRAINT "chk_member_position_dates" CHECK ("end_date" IS NULL OR "end_date" > "start_date")
);

-- ---------------------------------------------------------------------
-- Workload rubric (versioned)
-- ---------------------------------------------------------------------

CREATE TABLE "rubric_version" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(30) UNIQUE NOT NULL,
  "approved_meeting" varchar(50),
  "approved_on" date,
  "base_points" numeric(6,2) NOT NULL DEFAULT 200,
  "overall_cap" numeric(8,2) NOT NULL DEFAULT 2000,
  "min_required" numeric(8,2) NOT NULL DEFAULT 650,
  "min_teaching_credits" numeric(5,2) NOT NULL DEFAULT 6,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rubric_category" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "version_id" smallint NOT NULL,
  "code" varchar(5) NOT NULL,
  "name_th" varchar(100) NOT NULL,
  "cap" numeric(8,2) NOT NULL,
  "sort_order" smallint NOT NULL
);

CREATE TABLE "rubric_section" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" smallint NOT NULL,
  "parent_id" smallint,
  "code" varchar(10) NOT NULL,
  "name_th" varchar(255) NOT NULL,
  "cap" numeric(8,2),
  "max_entries" smallint,
  "sort_order" smallint NOT NULL
);

CREATE TABLE "rubric_item" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "section_id" smallint NOT NULL,
  "label_th" varchar(255) NOT NULL,
  "weight_mode" weight_mode NOT NULL DEFAULT 'fixed',
  "weight" numeric(6,4),
  "weight_min" numeric(8,4),
  "weight_max" numeric(8,4),
  "range_basis" range_basis,
  "assessor_position" position_code,
  "assessment_agg" assessment_agg NOT NULL DEFAULT 'none',
  "unit" quantity_unit NOT NULL,
  "unit_divisor" numeric(6,2) NOT NULL DEFAULT 1,
  "uses_participation" boolean NOT NULL DEFAULT false,
  "counts_teaching_credit" boolean NOT NULL DEFAULT false,
  "once_per_round" boolean NOT NULL DEFAULT false,
  "tier_min" integer,
  "tier_max" integer,
  "field_schema" jsonb,
  "is_active" boolean NOT NULL DEFAULT true,
  CONSTRAINT "chk_rubric_item_weight" CHECK (
    ("weight_mode" = 'fixed' AND "weight" IS NOT NULL)
    OR ("weight_mode" = 'ranged' AND "weight_min" IS NOT NULL AND "weight_min" <= "weight_max")
  )
);

-- ---------------------------------------------------------------------
-- Evaluation rounds + submissions
-- ---------------------------------------------------------------------

CREATE TABLE "evaluation_round" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rubric_version_id" smallint NOT NULL,
  "name_th" varchar(100) NOT NULL,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  "salary_effective_on" date NOT NULL,
  "academic_year" smallint NOT NULL,
  "semester" smallint,
  "submit_due_at" timestamptz,
  "is_open" boolean NOT NULL DEFAULT false,
  CONSTRAINT "chk_evaluation_round_period" CHECK ("period_end" > "period_start")
);

CREATE TABLE "submission" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "round_id" smallint NOT NULL,
  "lecturer_id" uuid NOT NULL,
  "status" submission_status NOT NULL DEFAULT 'draft',
  "rank_snapshot" academic_rank NOT NULL,
  "department_snapshot" smallint NOT NULL,
  "teaching_credits" numeric(6,2) NOT NULL DEFAULT 0,
  "raw_total" numeric(8,2) NOT NULL DEFAULT 0,
  "capped_total" numeric(8,2) NOT NULL DEFAULT 0,
  "submitted_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "submission_entry" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "submission_id" uuid NOT NULL,
  "item_id" smallint NOT NULL,
  "title" varchar(500),
  "course_code" varchar(15),
  "section_no" varchar(10),
  "student_count" integer,
  "data_source" data_source NOT NULL DEFAULT 'manual',
  "synced_at" timestamptz,
  "quantity" numeric(8,2) NOT NULL DEFAULT 1,
  "participation_pct" numeric(5,2) NOT NULL DEFAULT 100,
  "weight_applied" numeric(8,4),
  "credits" numeric(5,2),
  "score" numeric(8,2) NOT NULL DEFAULT 0,
  "details" jsonb,
  "note" text,
  "sort_order" smallint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "chk_submission_entry_participation" CHECK (
    "participation_pct" > 0 AND "participation_pct" <= 100
  ),
  CONSTRAINT "chk_submission_entry_quantity_score" CHECK ("quantity" > 0 AND "score" >= 0),
  CONSTRAINT "chk_submission_entry_student_count" CHECK (
    "student_count" IS NULL OR "student_count" >= 0
  )
);

CREATE TABLE "entry_assessment" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "entry_id" uuid NOT NULL,
  "assessor_id" uuid NOT NULL,
  "position_used" position_code NOT NULL,
  "value_given" numeric(8,4) NOT NULL,
  "comment" text,
  "assessed_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "entry_evidence" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "entry_id" uuid NOT NULL,
  "ref_code" varchar(50),
  "label" varchar(255),
  "s3_key" varchar(512) UNIQUE NOT NULL,
  "file_name" varchar(255) NOT NULL,
  "mime_type" varchar(100) NOT NULL,
  "size_bytes" bigint NOT NULL,
  "checksum" char(64),
  "status" evidence_status NOT NULL DEFAULT 'pending',
  "uploaded_by" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

-- ---------------------------------------------------------------------
-- Totals + sign-off
-- ---------------------------------------------------------------------

CREATE TABLE "submission_category_total" (
  "submission_id" uuid,
  "category_id" smallint,
  "raw_score" numeric(8,2) NOT NULL,
  "capped_score" numeric(8,2) NOT NULL,
  PRIMARY KEY ("submission_id", "category_id")
);

CREATE TABLE "submission_approval" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "submission_id" uuid NOT NULL,
  "signer_id" uuid NOT NULL,
  "role" signer_role NOT NULL,
  "decision" approval_decision NOT NULL,
  "comment" text,
  "signed_at" timestamptz NOT NULL DEFAULT (now())
);

-- ---------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------

CREATE INDEX ON "member_position" ("lecturer_id", "start_date");

CREATE INDEX ON "member_position" ("position", "department_id");

CREATE UNIQUE INDEX ON "rubric_category" ("version_id", "code");

CREATE UNIQUE INDEX ON "rubric_section" ("category_id", "code");

CREATE UNIQUE INDEX ON "submission" ("round_id", "lecturer_id");

CREATE INDEX ON "submission" ("round_id", "status");

CREATE INDEX ON "submission_entry" ("submission_id", "item_id");

CREATE INDEX ON "submission_entry" ("course_code", "section_no");

CREATE UNIQUE INDEX ON "entry_assessment" ("entry_id", "assessor_id");

CREATE INDEX ON "entry_evidence" ("entry_id");

CREATE INDEX ON "entry_evidence" ("status");

CREATE INDEX ON "submission_approval" ("submission_id", "signed_at");

CREATE INDEX "idx_entry_details" ON "submission_entry" USING GIN ("details");

CREATE INDEX "idx_position_active" ON "member_position" ("department_id", "position")
  WHERE "end_date" IS NULL;

CREATE INDEX "idx_submission_draft" ON "submission" ("lecturer_id") WHERE "status" = 'draft';

-- ---------------------------------------------------------------------
-- Foreign keys
-- ---------------------------------------------------------------------

ALTER TABLE "lecturer" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "member_position" ADD FOREIGN KEY ("lecturer_id") REFERENCES "lecturer" ("lecturer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "member_position" ADD FOREIGN KEY ("department_id") REFERENCES "department" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_category" ADD FOREIGN KEY ("version_id") REFERENCES "rubric_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_section" ADD FOREIGN KEY ("category_id") REFERENCES "rubric_category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_section" ADD FOREIGN KEY ("parent_id") REFERENCES "rubric_section" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rubric_item" ADD FOREIGN KEY ("section_id") REFERENCES "rubric_section" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evaluation_round" ADD FOREIGN KEY ("rubric_version_id") REFERENCES "rubric_version" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission" ADD FOREIGN KEY ("round_id") REFERENCES "evaluation_round" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission" ADD FOREIGN KEY ("lecturer_id") REFERENCES "lecturer" ("lecturer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission" ADD FOREIGN KEY ("department_snapshot") REFERENCES "department" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_entry" ADD FOREIGN KEY ("submission_id") REFERENCES "submission" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_entry" ADD FOREIGN KEY ("item_id") REFERENCES "rubric_item" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_assessment" ADD FOREIGN KEY ("entry_id") REFERENCES "submission_entry" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_assessment" ADD FOREIGN KEY ("assessor_id") REFERENCES "lecturer" ("lecturer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_evidence" ADD FOREIGN KEY ("entry_id") REFERENCES "submission_entry" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entry_evidence" ADD FOREIGN KEY ("uploaded_by") REFERENCES "lecturer" ("lecturer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_category_total" ADD FOREIGN KEY ("submission_id") REFERENCES "submission" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_category_total" ADD FOREIGN KEY ("category_id") REFERENCES "rubric_category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_approval" ADD FOREIGN KEY ("submission_id") REFERENCES "submission" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submission_approval" ADD FOREIGN KEY ("signer_id") REFERENCES "lecturer" ("lecturer_id") DEFERRABLE INITIALLY IMMEDIATE;

-- ---------------------------------------------------------------------
-- Entries can only change while their submission is a draft
-- ---------------------------------------------------------------------

CREATE FUNCTION "submission_entry_draft_only"() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  target_submission uuid := CASE WHEN TG_OP = 'DELETE' THEN OLD.submission_id ELSE NEW.submission_id END;
  current_status submission_status;
BEGIN
  SELECT status INTO current_status FROM submission WHERE id = target_submission;
  -- NOT FOUND: the parent submission is being deleted (ON DELETE CASCADE), so let it through.
  IF FOUND AND current_status <> 'draft' THEN
    RAISE EXCEPTION 'submission % is %, entries can only change while it is a draft',
      target_submission, current_status
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

CREATE TRIGGER "trg_submission_entry_draft_only"
  BEFORE INSERT OR UPDATE OR DELETE ON "submission_entry"
  FOR EACH ROW EXECUTE FUNCTION "submission_entry_draft_only"();

-- ---------------------------------------------------------------------
-- Score per rubric section, capped at the section's cap
-- ---------------------------------------------------------------------

CREATE VIEW "v_section_total" AS
SELECT
  e.submission_id,
  s.id AS section_id,
  SUM(e.score) AS raw_score,
  LEAST(SUM(e.score), COALESCE(s.cap, SUM(e.score))) AS capped_score
FROM submission_entry e
JOIN rubric_item i ON i.id = e.item_id
JOIN rubric_section s ON s.id = i.section_id
GROUP BY e.submission_id, s.id, s.cap;

COMMIT;
