#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  if command -v wslview >/dev/null 2>&1; then
    wslview "$url" >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
  elif command -v explorer.exe >/dev/null 2>&1; then
    explorer.exe "$url" >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url" >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
  elif command -v open >/dev/null 2>&1; then
    open "$url" >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
  else
    warn "couldn't open a browser — visit it manually: $url"
  fi
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || { warn "invalid environment key: $key"; return 1; }
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || { warn "refusing multiline value for $key"; return 1; }
  touch "$ENV_FILE"
  tmp=$(mktemp)
  if grep -vE "^${key}=" "$ENV_FILE" > "$tmp"; then
    :
  else
    local grep_status=$?
    if [[ "$grep_status" -ne 1 ]]; then
      rm -f "$tmp"
      warn "couldn't read $ENV_FILE safely; leaving it unchanged"
      return "$grep_status"
    fi
  fi
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "CS361 V2 AWS foundation setup"

stage "AWS login boundary"
say "This wizard never asks for AWS access keys or secret values."
step "Install AWS CLI v2 if it is not installed yet."
open_url "https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
step "Configure AWS login locally using your team's approved method, such as aws configure sso."
step "Do not paste AWS access keys, secret access keys, session tokens, or DB passwords into chat or docs."
pause "Press Enter after AWS CLI is installed and login/profile is ready."

stage "Collect non-secret deployment inputs"
say "These values are not secrets, but they should still be copied carefully from AWS Console."
open_url "https://ap-southeast-1.console.aws.amazon.com/vpcconsole/home?region=ap-southeast-1#vpcs:"
ask AWS_REGION "AWS region [default ap-southeast-1]:"
AWS_REGION="${AWS_REGION:-ap-southeast-1}"
ask CFN_STACK_NAME "CloudFormation stack name [default cs361-v2-aws-foundation-dev]:"
CFN_STACK_NAME="${CFN_STACK_NAME:-cs361-v2-aws-foundation-dev}"
ask VPC_ID "Paste the VPC ID:"
ask PRIVATE_SUBNET_IDS "Paste at least two private subnet IDs, comma-separated:"
ask DB_ENGINE_VERSION "Aurora PostgreSQL engine version [default 16.6]:"
DB_ENGINE_VERSION="${DB_ENGINE_VERSION:-16.6}"
ask MIN_CAPACITY "Min ACU [default 0.5; use 0 only if engine supports auto-pause]:"
MIN_CAPACITY="${MIN_CAPACITY:-0.5}"
ask MAX_CAPACITY "Max ACU [default 2]:"
MAX_CAPACITY="${MAX_CAPACITY:-2}"

stage "Write local parameter/env helpers"
say "The wizard writes only local helper files. Review before running deployment."
write_env AWS_REGION "$AWS_REGION"
write_env CFN_STACK_NAME "$CFN_STACK_NAME"
write_env VPC_ID "$VPC_ID"
write_env PRIVATE_SUBNET_IDS "$PRIVATE_SUBNET_IDS"
write_env DB_ENGINE_VERSION "$DB_ENGINE_VERSION"
write_env MIN_CAPACITY "$MIN_CAPACITY"
write_env MAX_CAPACITY "$MAX_CAPACITY"
cat > infra/v2/parameters.dev.local.json <<PARAMS
[
  {"ParameterKey":"ProjectName","ParameterValue":"cs361-v2"},
  {"ParameterKey":"Environment","ParameterValue":"dev"},
  {"ParameterKey":"VpcId","ParameterValue":"$VPC_ID"},
  {"ParameterKey":"PrivateSubnetIds","ParameterValue":"$PRIVATE_SUBNET_IDS"},
  {"ParameterKey":"DBName","ParameterValue":"cs361v2"},
  {"ParameterKey":"DBMasterUsername","ParameterValue":"cs361v2admin"},
  {"ParameterKey":"DBEngineVersion","ParameterValue":"$DB_ENGINE_VERSION"},
  {"ParameterKey":"MinCapacity","ParameterValue":"$MIN_CAPACITY"},
  {"ParameterKey":"MaxCapacity","ParameterValue":"$MAX_CAPACITY"},
  {"ParameterKey":"SecondsUntilAutoPause","ParameterValue":"600"},
  {"ParameterKey":"LogRetentionDays","ParameterValue":"14"}
]
PARAMS
say "Wrote infra/v2/parameters.dev.local.json"

stage "Deploy CloudFormation"
say "Run this command from the repo root after reviewing the parameter file:"
step "aws cloudformation deploy --region $AWS_REGION --stack-name $CFN_STACK_NAME --template-file infra/v2/aws-foundation.yaml --parameter-overrides ProjectName=cs361-v2 Environment=dev VpcId=$VPC_ID PrivateSubnetIds=$PRIVATE_SUBNET_IDS DBName=cs361v2 DBMasterUsername=cs361v2admin DBEngineVersion=$DB_ENGINE_VERSION MinCapacity=$MIN_CAPACITY MaxCapacity=$MAX_CAPACITY SecondsUntilAutoPause=600 LogRetentionDays=14 --capabilities CAPABILITY_NAMED_IAM"
pause "Press Enter after the stack deploy succeeds."

stage "Collect stack outputs"
say "Run this command and copy the output values into the prompts:"
step "aws cloudformation describe-stacks --region $AWS_REGION --stack-name $CFN_STACK_NAME --query 'Stacks[0].Outputs'"
ask DB_CLUSTER_ARN "Paste DBClusterArn:"
ask DB_SECRET_ARN "Paste DBSecretArn:"
ask DB_NAME "Paste DBName [default cs361v2]:"
DB_NAME="${DB_NAME:-cs361v2}"
ask DATA_BUCKET_NAME "Paste DataBucketName:"
write_env DB_CLUSTER_ARN "$DB_CLUSTER_ARN"
write_env DB_SECRET_ARN "$DB_SECRET_ARN"
write_env DB_NAME "$DB_NAME"
write_env DATA_BUCKET_NAME "$DATA_BUCKET_NAME"
write_env LOG_LEVEL "INFO"
write_env ENVIRONMENT "dev"

stage "Verify Data API"
say "Run the verification script using the values saved in $ENV_FILE."
step "source $ENV_FILE"
step "scripts/check-v2-aws-foundation.sh"
pause "Press Enter after SELECT 1 succeeds."
say "After verification, update docs/v2/aws-foundation.md and docs/v2/aws-foundation-evidence.md with the safe outputs."

finish
