"""Shared helpers for table models.

The schema's source of truth is database/migrations/ (002_lecturer_profile.sql and
003_faculty_workload.sql); models mirror it so the ORM and the real tables agree.
"""

import uuid
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

import sqlalchemy as sa
from sqlmodel import Field


def utc_now() -> datetime:
    return datetime.now(UTC)


def fk(target: str, *, cascade: bool = True) -> sa.ForeignKey:
    """Foreign key exactly as in the schema: DEFERRABLE INITIALLY IMMEDIATE, plus
    ON DELETE CASCADE unless `cascade=False` (most workload tables in 003 do not cascade)."""
    return sa.ForeignKey(
        target,
        ondelete="CASCADE" if cascade else None,
        deferrable=True,
        initially="IMMEDIATE",
    )


def identity_pk(sa_type: type[sa.Integer] = sa.Integer) -> Any:
    """`GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`; leave it None and the DB assigns it."""
    return Field(default=None, primary_key=True, sa_type=sa_type, sa_column_args=[sa.Identity()])


def uuid_pk() -> Any:
    """`uuid PRIMARY KEY DEFAULT (gen_random_uuid())`."""
    return Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        sa_column_kwargs={"server_default": sa.text("gen_random_uuid()")},
    )


def pg_enum(enum_cls: type[StrEnum], name: str) -> sa.Enum:
    """A column of the PostgreSQL enum type `name`, storing the members' values
    (e.g. 'dept_chair'), not their Python names."""
    return sa.Enum(enum_cls, name=name, values_callable=lambda cls: [m.value for m in cls])


def timestamp_field(*, auto_update: bool = False) -> Any:
    """`timestamptz DEFAULT (now())`. The schema has no trigger, so the ORM refreshes
    `updated_at` on UPDATE when `auto_update=True`."""
    column_kwargs: dict[str, Any] = {"server_default": sa.func.now()}
    if auto_update:
        column_kwargs["onupdate"] = utc_now
    return Field(
        default_factory=utc_now,
        sa_type=sa.DateTime(timezone=True),
        sa_column_kwargs=column_kwargs,
    )
