"""Shared helpers for table models.

The schema's source of truth is database/migrations/002_lecturer_profile.sql;
models mirror it so the ORM and the real tables agree.
"""

from datetime import UTC, datetime
from typing import Any

import sqlalchemy as sa
from sqlmodel import Field


def utc_now() -> datetime:
    return datetime.now(UTC)


def fk(target: str) -> sa.ForeignKey:
    """Foreign key exactly as in the schema: ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE."""
    return sa.ForeignKey(target, ondelete="CASCADE", deferrable=True, initially="IMMEDIATE")


def identity_pk(sa_type: type[sa.Integer] = sa.Integer) -> Any:
    """`GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`; leave it None and the DB assigns it."""
    return Field(default=None, primary_key=True, sa_type=sa_type, sa_column_args=[sa.Identity()])


def timestamp_field(*, auto_update: bool = False) -> Any:
    """`timestamptz DEFAULT (now())`. The schema has no trigger, so the ORM refreshes
    `updated_at` on UPDATE when `auto_update=True`."""
    column_kwargs: dict[str, Any] = {"server_default": sa.func.now()}
    if auto_update:
        column_kwargs["onupdate"] = utc_now
    return Field(
        default_factory=utc_now,
        sa_type=sa.DateTime(timezone=True),
        sa_column_kwargs=column_kwargs,
    )
